# Generated by Django 5.2.3 on 2025-06-23 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='username',
        ),
        migrations.AddField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default='2025-12-01'),
        ),
    ]
